### ISSUE TITLE
infinite blocks with builders wand

### ISSUE THREAD

**Issue by rahangar** [Darkosto/InvasionIssues#227] opened 2017-04-30 01:55 UTC
Not sure if this is a problem with all block types or if only the tier 5 hardened blocks that I'm using is affected.  With several stacks of tier 5 hardened blocks in my inventory, I try extending a wall.  The blocks are placed, but the number of blocks in my inventory does not change.  This effectively provides infinite blocks.

**Comment by tenshinoshi** [comment] 2017-05-02 16:18
I can confirm that it is any type of block. You need an # of that block in your inventory that you are trying to place.  This is an issue with ExtraUtilities itself. I would suggest disabling the recipe for the ExtraUtilities Builder's Wand, especially since there are alternatives in the pack for it.

Here is a link to one of the many open tickets on the ExtraUtilities GitHub.
[https://github.com/scalda/FoolCraft/issues/404](url)

**Comment by Darkosto** [comment] 2017-05-05 23:10
Fixed in 1.0.6, thank you!

**Closed as completed by Darkosto** 2017-05-05 23:10 UTC
