### ISSUE TITLE
Engineer's Manual crash

### ISSUE THREAD

**Issue by amezh** [Darkosto/InvasionIssues#32] opened 2017-03-29 01:00 UTC
Open manual -> go to Metal Press -> hover "?" button  (some times it works, so hover few times) 
```
[01:46:53] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=damage, clazz=class java.lang.Integer, values=[0, 1, 2]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=damage, clazz=class java.lang.Integer, values=[0, 1, 2]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
	at breakabletables.inventory.ContainerWorkbenchBreakable$1.func_82870_a(ContainerWorkbenchBreakable.java:29) ~[ContainerWorkbenchBreakable$1.class:?]
	at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:119) ~[abm.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:258) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_75133_b(Container.java:525) ~[abd.class:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:267) ~[abd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:1112) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:33) ~[ir.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(SourceFile:10) ~[ir.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[01:55:59] [Server thread/INFO]: Server Backup started!
[01:55:59] [Server thread/INFO]: Turned off world auto-saving
```
[2017-03-29-2.log.gz](https://github.com/Darkosto/InvasionIssues/files/877473/2017-03-29-2.log.gz)

**Comment by Darkosto** [comment] 2017-03-29 19:59
Please use pastebin.com to bring crash reports into this issue tracker. 

I'll take a look at this and try to reproduce.

**Comment by Darkosto** [comment] 2017-03-29 21:35
I can't reproduce this. Do you have a crash report?

**Comment by Darkosto** [comment] 2017-04-02 15:15
Still can't reproduce and I have no crash report to go off of. Closing the issue.

**Closed as completed by Darkosto** 2017-04-02 15:15 UTC
Labels: ¯\_(ツ)_/¯
