### ISSUE TITLE
Empty airdrops

### ISSUE THREAD

**Issue by AseGarcia** [Darkosto/InvasionIssues#128] opened 2017-04-06 11:23 UTC
Hello,

I've been playing for 3-4 days this modpack and **all** the beacons I've activated so far have given me empty air drops. I've tried starting new worlds, reinstalling modpack, etc...

Does it happen to anyone else?

Regards

**Comment by Zunth5** [comment] 2017-04-08 18:20
Got this too on a server setup.

**Comment by Darkosto** [comment] 2017-04-10 18:32
Restarting a world, or reinstalling should fix this issue.

This issue is hardly reproducible on my end and there's not much else I can do, but I have had 99% of the reports of this fixed by new worlds or reinstall.

**Closed as completed by Darkosto** 2017-04-10 18:32 UTC

**Comment by Zunth5** [comment] 2017-04-10 19:04
Turns out the server pack didn't have all of the mods in it. Causing the server to "sorta" be installed but without the survivalist mod and others
